version: 2.1
orbs:
  node: circleci/node@5.2
jobs:
  test-v12:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: "12.22"
      - run:
          name: Build
          command: npm install
      - run:
          name: Test
          command: npm install
      - run:
          name: Verify test
          command: echo "Build completed successfully!"
  test-v14:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: "14.21"
      - run:
          name: Test
          command: npm install
      - run:
          name: Verify test
          command: echo "Build completed successfully!"
  test-v16:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: "16.20"
      - run:
          name: Test
          command: npm install
      - run:
          name: Verify test
          command: echo "Build completed successfully!"
  test-v18:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: "18.20"
      - run:
          name: Test
          command: npm install
      - run:
          name: Verify test
          command: echo "Build completed successfully!"
  test-v20:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: "20.18"
      - run:
          name: Test
          command: npm install
      - run:
          name: Verify test
          command: echo "Build completed successfully!"
  test-v22:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: "22.11"
      - run:
          name: Test
          command: npm install
      - run:
          name: Verify test
          command: echo "Build completed successfully!"
workflows:
  build_and_test:
    jobs:
      - test-v16
      - test-v18
      - test-v20
      - test-v22
